# Generated by Django 5.2.11 on 2026-02-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webmentions", "0002_alter_webmentionauthor_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmarkwebmention",
            options={},
        ),
        migrations.AlterModelOptions(
            name="likewebmention",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mentionwebmention",
            options={},
        ),
        migrations.AlterModelOptions(
            name="replywebmention",
            options={},
        ),
        migrations.AlterModelOptions(
            name="repostwebmention",
            options={},
        ),
        migrations.AlterModelOptions(
            name="rsvpwebmention",
            options={},
        ),
    ]
