# Generated by Django 6.0.2 on 2026-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0014_guestbookformpage_tags_guestbookindexpage_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="message",
            field=models.TextField(
                help_text="Supports basic Markdown and HTML. Max 2000 characters. GIFs allowed from giphy/tenor/imgbb.",
                max_length=2000,
            ),
        ),
    ]
